- name: Install base packages
  apt: pkg={{item}} state=installed update-cache=yes
  with_items:
    - build-essential
    - python3
    - python3-dev
    - python-virtualenv
    - python-psycopg2
    - python-httplib2
    - postgresql
    - postgresql-9.5-debversion # FIXME hardcoded version; change for new ubuntu versions
    - libpq-dev
    - libldap2-dev
    - libsasl2-dev
    - apache2
    - libapache2-mod-wsgi
    - rabbitmq-server
    - git

- command: a2enmod proxy proxy_balancer lbmethod_byrequests proxy_http rewrite ssl cgid
  register: result
  changed_when: "'Enabling module' in result.stdout"
  notify: restart-apache2

- name: detect SSL cert
  shell: "ls -1d /var/lib/dehydrated/certs/{{inventory_hostname}} || true"
  register: ssl
  changed_when: False
